### PR TITLE
feat: retry when delegate load error

### PR DESCRIPTION
**Pull request by HuberTRoy**
## Description

Better error handling for delegate for now.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## UI Changes

SCR-20230830-jone

### CODE REVIEW

**Comment by mzxyz** [comment]
Is the problem caused by connecting incorrect network?

**Comment by HuberTRoy** [comment]
@mzxyz 

Oh, right. and I don't get any errors in here except the network error. Maybe in future will have kind of errors. Changed to `Error`.

**Comment by mzxyz** [comment]
I think the problem here is because the `indexers` page is public and no wallet connection required, but to get the status for each indexer need to make the RPC call to the connected network.

I would recommend to mask  the whole `action` column as `-` if there has no network connection.

**Comment by HuberTRoy** [comment]
@mzxyz 

Yeah, right. and I have been fix the bug that no wallet connection in #533 , so in this pr I want to handle if the user have connected the wallet but still cause an error.

**Review by mzxyz — APPROVED** [review]

**Pull request merged**
