### PR TITLE
Changed the Mobile interface a little

### PR DESCRIPTION
**Pull request by duchuytb9x**
## Description

Change the interface of Dashboard, My-projects, Node-operators. Do not make changes on Desktop

## Test cases:

Please describe tested cases.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvements (ie: code cleaning or remove unused codes or performance issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## UI Changes

Add before and after changes for UI if needed.

|before|after|
|-|-|
|Screenshot_26-4-2024_225955_app subquery network|Screenshot_26-4-2024_225921_127 0 0 1|
|Screenshot_26-4-2024_23126_app subquery network|Screenshot_26-4-2024_23045_127 0 0 1|
|Screenshot_26-4-2024_233333_app subquery network|Screenshot_26-4-2024_233317_127 0 0 1|
|Screenshot_28-4-2024_174919_app subquery network|Screenshot_28-4-2024_17495_127 0 0 1|

### CODE REVIEW

**Comment by duchuytb9x** [comment]
function getWindowDimensions() you can write in one place and use it in many places!

**Comment by HuberTRoy** [comment]
Thanks for your contribute, looks great, can you please made some adjust:

1. Please change the ```
.xxx { @media {...} }
.yyy { @media {...} }
``` to ```
@media { 
    .xxx {...} 
    .yyy {...}
}
```

2. Set a class name for elements which need to change style on Mobile.
3. Please don't copy the same code everywhere, use `https://ahooks.js.org/hooks/use-size` or `https://ahooks.js.org/hooks/use-responsive` replace `getWindowDimensions`.

**Comment by duchuytb9x** [comment]
adjust completed. You can check change

**Comment by HuberTRoy** [comment]
Thanks for your work~.

**Review by HuberTRoy — APPROVED** [review]

**Pull request merged**
